name: Test
on:
  # schedule:
  # - cron: "0 4 * * *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Runs this workflow
      env:
        SEARCH_GITHUB_TOKEN: ${{ secrets.SEARCH_GITHUB_TOKEN }}
      uses:  j82w/code-organizer-merge-on-green@master

